name: Continuos Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Prepare package building
        run: |
          pnpm build \
            --workspace-concurrency=1 \
            --filter='./packages/common' \
            --filter='./packages/types' \
            --filter='./packages/system' \
            --filter='./packages/access-control' \
            --filter='./packages/security' \
            --filter='./packages/mailing' \
            --filter='./packages/api' \
            --filter='./packages/server' 2>&1 > /dev/null || true
      - name: Actually build packages
        run: |
          pnpm --filter '*' build
          find packages -mindepth 1 -maxdepth 1 \
            -exec bash -c 'a={}; cp -r $a/dist node_modules/@sonata-api/${a//packages\//} 2>/dev/null || true' \;
      - name: Run tests
        run: pnpm --filter '*' test
